### ISSUE TITLE
compile 'com.github.mcxtzhang:SuspensionIndexBar:V1.0.0' 这个不能同步什么情况上传了吗

### ISSUE THREAD

**Issue by douya40** [mcxtzhang/SuspensionIndexBar#12]
compile 'com.github.mcxtzhang:SuspensionIndexBar:V1.0.0' 这个不能同步什么情况上传了吗

**Comment by mcxtzhang** [comment]
请check一下你的网络 或者 配置文件是否正确，我可以正常引入。

# 引入
Step 1. Add the JitPack repository to your build file
Add it in your root build.gradle at the end of repositories:
```
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```
Step 2. Add the dependency
```
	dependencies {
	        compile 'com.github.mcxtzhang:SuspensionIndexBar:V1.0.0'
	}
```
