### ISSUE TITLE
com.github.mcxtzhang:SwipeDelMenuLayout:V1.2.2不能同步

### ISSUE THREAD

**Issue by douya40** [mcxtzhang/SuspensionIndexBar#13]
Error:(26, 13) Failed to resolve: com.github.mcxtzhang:SwipeDelMenuLayout:V1.2.2
<a href="openFile:C:/Users/Administrator/AndroidStudioProjects/MyApplication26/SuspensionIndexBarapp/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by mcxtzhang** [comment]
按照步骤引入吧。 如果好用还请给个star。
# 引入
Step 1. Add the JitPack repository to your build file
Add it in your root build.gradle at the end of repositories:
```
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```
Step 2. Add the dependency
```
	dependencies {
	       compile 'com.github.mcxtzhang:SwipeDelMenuLayout:V1.2.3'
	}
```
