### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by hegelsu** [mcxtzhang/SuspensionIndexBar#21]
我一直在用的库：https://github.com/truizlop/SectionedRecyclerView
因为也一直没用到悬停的功能和需求，但想想，今天看到这个库很是喜欢，但又不舍原来的库，如果能直接把头部定制，尾部定制，悬停，搜索及IndexBar全集成一个那不完美了，当然我也是一个喜欢在Git上找库不愿花时间去自己造轮子的人，发个美好愿景，最后再次感谢作者的奉献精神，你的滑动删除库太好用我无法用语言来诉说。

**Comment by mcxtzhang** [comment]
关于Header、footer https://github.com/mcxtzhang/all-base-adapter
我这个库可以做到。

这些功能毫无耦合性，每个都像机关枪，拿过来就用，何必要造一个坦克，配上N把这种机枪呢，那样如果想加另外机关枪， 就很难了。  

你发的这个库 就是这个问题。

**Comment by mcxtzhang** [comment]
封装代表了一定程度的易用快速，同时也带来了封闭性，如果封装的不好，扩展就不太方便，
1 要么联系原作者加入
2 要么自己修改源代码
3 换库~

**Comment by hegelsu** [comment]
嗯，同意作者的观点。https://github.com/mcxtzhang/all-base-adapter这个库我后面有时间研究下。
